default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: writer_app_user
  password: ryo1204897
  host: localhost

development:
  <<: *default
  database: writer_task_management_development

test:
  <<: *default
  database: writer_task_management_test

production:
  <<: *default
  database: writer_task_management_production
  url: <%= ENV['DATABASE_URL'] %>